name: voice_gpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  avatar_glow: ^2.0.2
  chat_bubbles: ^1.4.1
  chat_gpt_sdk: ^2.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_config: ^2.0.0
  flutter_spinkit: ^5.1.0
  go_router: ^6.5.2
  http: ^0.13.5
  intl: ^0.18.0
  shared_preferences: ^2.1.0
  speech_to_text: ^6.1.1
  text_to_speech: ^0.2.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/countries/